<a href="https://colab.research.google.com/github/INmais/Energy_Services_2022/blob/main/Energy_Services_Intro_APIs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to requests and API's

### APIs : What and why
    
An API (Application Programming interface) is a way for two different applications to communicate. Whilst the term applies to any two programs we are using it to refer to the API of a web service that provides data.

To retrieve data from an API, a request to a remote web server is made.

For example, if you want to build an application which plots stock prices, you would use the API of something like google finance to request the current stock prices.

APIs are useful where:
* Data is changing quickly, e.g. stock prices
* The whole dataset is not required, e.g. the tweets of one user
* Repeated computation is involved, e.g. Spotify API that tells you the genre of a piece of music

#### REST

Most API's you come across will be RESTful, i.e. they provide a REST (REpresentational State Transfer) interface.

REST uses standard HTTP commands which means that getting data from an API is similar to accessing a webpage. 

For example, When you type `www.duckduckgo.com` in your browser, your browser is asking the `www.duckduckgo.com` server for a webpage by making a `GET` HTTP (Hypertext Transfer Protocol) request. Making a `GET` request to a RESTful API instead retrieves data (rather than a webpage).

Similarly, while your browser uses `POST` to submit the contents of a form, REST APIs use `POST` to update data.

REST APIs also uses other HTTP commmands such as `PUT` - for creating data - and `DELETE` - for removing data.

HTTP is a text-based protocol (the response is always text) and could return a response in any format - this is typically found in the API documentation - though data is more often than not returned in JSON format.

As they are used to retrieve data `GET` requests are the most commonly used type of request, therefore we will restrict ourselves to `GET` in this tutorial.

#### JSON

JSON (JavaScript Object Notation) is a format for sending data, that is meant to be human readable and easy to parse (It was derived from JavaScript but is language-independent).

It uses attribute-value pairs (e.g. python dictionaries `{"class": "Energy Services", "year": 2022}`) and array data-types (e.g. python lists `[1, 2, 3]`)

Example JSON representation :
```
{
  "Class": "Energy Services",
  "year": 2022,
  "city": "Lisbon"
  "addresses":[
      {
        "streetAddress": "Av. Rovisco Pais, 1",
        "city": "Lisboa",
        "postalCode": "1200",
        "country": "PT"]
        }
}
```

In [1]:
import json
# a Python object (dict):
x = {
  "Class": "Energy Services",
  "year": 2022,
  "city": "Lisbon"
}

# convert into JSON:
y = json.dumps(x)

# the result is a JSON string:
print(y)

{"Class": "Energy Services", "year": 2022, "city": "Lisbon"}

#### Status codes

So we've sent off some mystery `GET` request but how do we know the request was successful?

Servers issue numeric [status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) in response to HTTP requests that indicate whether a request has been successfully completed.

Some common ones relating to `GET` requests are:
* `200` - Success
* `300` - The API is redirecting to a different endpoint
* `400` - Bad request
* `401` - Not authenticated
* `403` - Forbidden
* `404` - Not found
* `429` - Too many requests

### List of API's

Massive list [**here**](https://github.com/public-apis/public-apis)

### API wrapper libraries

Massive list [**here**](https://github.com/realpython/list-of-python-api-wrappers).

For example, geo-code location data with [`geopy`](https://github.com/geopy/geopy) :

In [ ]:
#! pip install numpy==1.21.2
#! pip install pandas==1.1.0

In [2]:
import numpy as np
print(np.__version__)

1.21.2

In [3]:
# libraries
import urllib.request
import json
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [4]:
api_link="https://api.eot.pt/api/pulse/last/power?key=4787F1QSP6QUEOQZ"

req=urllib.request.urlopen(api_link)
req_body=req.read()
value=json.loads(req_body.decode("utf-8"))
print(value/1000, 'kW')

422.78803999999997 kW

In [5]:
#API for North Tower
api_link="https://energist.tecnico.ulisboa.pt/api/v1/m2m/4d7768b47bfbf9e32c975f15df498370"

req=urllib.request.urlopen(api_link)
req_body=req.read()
j=json.loads(req_body.decode("utf-8"))
o=j["outputs"]
i=o[0]
value=pd.DataFrame(i)

value2=value.iloc[0]["results"]
print(value2/1000 ,"[kWh]")

848.4589279999999 [kWh]

In [28]:
#API for IST Total
api_link="https://api.eot.pt/api/meter/feed.json?key=FHVAL4DWEXBQ3XNP&results=1000"
req=urllib.request.urlopen(api_link)
req_body=req.read()
#

In [7]:
j=json.loads(req_body.decode("utf-8"))

In [8]:
j.keys()

dict_keys(['meter', 'channels'])

In [9]:
o=j["channels"]

In [10]:
value=pd.DataFrame(o)
value

,name,last_entry_id,last_write_at,feeds
0,vocs,423337,2022-04-17 18:20:21 UTC,"[{'created_at': '2022-04-14 06:52:01 UTC', 'en..."
1,pcpm10,423337,2022-04-17 18:20:21 UTC,"[{'created_at': '2022-04-14 06:52:01 UTC', 'en..."
2,co2,423337,2022-04-17 18:20:21 UTC,"[{'created_at': '2022-04-14 06:52:01 UTC', 'en..."
3,movc,423337,2022-04-17 18:20:21 UTC,"[{'created_at': '2022-04-14 06:52:01 UTC', 'en..."
4,vbat,423337,2022-04-17 18:20:21 UTC,"[{'created_at': '2022-04-14 06:52:01 UTC', 'en..."
5,temperature,423337,2022-04-17 18:20:21 UTC,"[{'created_at': '2022-04-14 06:52:01 UTC', 'en..."
6,humidity,423337,2022-04-17 18:20:21 UTC,"[{'created_at': '2022-04-14 06:52:01 UTC', 'en..."
7,pcpm25,423337,2022-04-17 18:20:21 UTC,"[{'created_at': '2022-04-14 06:52:01 UTC', 'en..."

In [11]:
i=o[5]["feeds"]  #5 temperaturee
temperature=pd.DataFrame(i)
temperature

                  created_at  entry_id  value
0    2022-04-14 06:52:01 UTC    422338  21.51
1    2022-04-14 06:57:01 UTC    422339   21.5
2    2022-04-14 07:02:01 UTC    422340  21.53
3    2022-04-14 07:07:01 UTC    422341  21.54
4    2022-04-14 07:12:01 UTC    422342  21.55
..                       ...       ...    ...
995  2022-04-17 18:00:22 UTC    423333  25.78
996  2022-04-17 18:05:22 UTC    423334  25.76
997  2022-04-17 18:10:22 UTC    423335  25.73
998  2022-04-17 18:15:22 UTC    423336  25.65
999  2022-04-17 18:20:21 UTC    423337  25.62

[1000 rows x 3 columns]

In [12]:
temperature['created_at'] = pd.to_datetime(temperature['created_at'])

In [13]:
temperature = temperature.set_index('created_at')

In [14]:
temperature

                           entry_id  value
created_at
2022-04-14 06:52:01+00:00    422338  21.51
2022-04-14 06:57:01+00:00    422339   21.5
2022-04-14 07:02:01+00:00    422340  21.53
2022-04-14 07:07:01+00:00    422341  21.54
2022-04-14 07:12:01+00:00    422342  21.55
...                             ...    ...
2022-04-17 18:00:22+00:00    423333  25.78
2022-04-17 18:05:22+00:00    423334  25.76
2022-04-17 18:10:22+00:00    423335  25.73
2022-04-17 18:15:22+00:00    423336  25.65
2022-04-17 18:20:21+00:00    423337  25.62

[1000 rows x 2 columns]

In [15]:
temperature['value'] = temperature['value'].apply(lambda x: float(x))

In [16]:
temperature['value']

created_at
2022-04-14 06:52:01+00:00    21.51
2022-04-14 06:57:01+00:00    21.50
2022-04-14 07:02:01+00:00    21.53
2022-04-14 07:07:01+00:00    21.54
2022-04-14 07:12:01+00:00    21.55
                             ...
2022-04-17 18:00:22+00:00    25.78
2022-04-17 18:05:22+00:00    25.76
2022-04-17 18:10:22+00:00    25.73
2022-04-17 18:15:22+00:00    25.65
2022-04-17 18:20:21+00:00    25.62
Name: value, Length: 1000, dtype: float64

In [17]:
#temperature['value'].plot(linewidth=0.5);

In [18]:
temp=float(temperature.value[0])

print("Room V1.10 - Temperature:", temp,"ºC")

Room V1.10 - Temperature: 21.51 ºC

# NREL API

Documentation: https://developer.nrel.gov/

In [19]:
import pandas as pd
api_link2="https://developer.nrel.gov/api/solar/solar_resource/v1.json?api_key=DEMO_KEY&lat=40&lon=-105"
req=urllib.request.urlopen(api_link2)
req_body=req.read()

j=json.loads(req_body.decode("utf-8"))
o=j["outputs"]
i=o["avg_dni"]
df=pd.DataFrame(i)
fig=px.bar(df,x=df.index,y=df.monthly )
fig.show()
#fig1=plt.bar(df.index,df.monthly)

## ENTSOE API
Reading from an API ENTSOE Transparency Platform: https://transparency.entsoe.eu/dashboard/show

Using ENTSOE API ("To request access to the Restful API, please register on the Transparency Platform and send an email to transparency@entsoe.eu with “Restful API access” in the subject line. Indicate the email address you entered during registration in the email body. The ENTSO-E Helpdesk will make their best efforts to respond to your request within 3 working days."

user guide: https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html

In [20]:
! pip install entsoe-py==0.4.1 #entsoe API
#or Force pandas>=1.4.0 in requirements #163

Requirement already satisfied: entsoe-py==0.4.1 in /usr/local/lib/python3.7/dist-packages (0.4.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from entsoe-py==0.4.1) (2018.9)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from entsoe-py==0.4.1) (1.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from entsoe-py==0.4.1) (2.23.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from entsoe-py==0.4.1) (4.6.3)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas->entsoe-py==0.4.1) (1.21.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->entsoe-py==0.4.1) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->entsoe-py==0.4.1) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->entsoe-py==0.4.1) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->entsoe-py==0.4.1) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->entsoe-py==0.4.1) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->entsoe-py==0.4.1) (2021.10.8)

In [21]:
from entsoe import EntsoePandasClient
from entsoe import EntsoeRawClient
import pandas as pd
client = EntsoePandasClient(api_key='*******') #have to have a key
start = pd.Timestamp('20211201', tz ='Europe/Lisbon')
end = pd.Timestamp('20220301', tz ='Europe/Lisbon')
country_code = 'PT'  # Portugal

In [22]:
#day-ahead market prices (€/MWh)
client.query_day_ahead_prices(country_code, start=start,end=end)

2021-12-01 00:00:00+00:00    259.05
2021-12-01 01:00:00+00:00    246.25
2021-12-01 02:00:00+00:00    232.97
2021-12-01 03:00:00+00:00    200.30
2021-12-01 04:00:00+00:00    200.00
                              ...
2022-02-28 20:00:00+00:00    324.09
2022-02-28 21:00:00+00:00    291.18
2022-02-28 22:00:00+00:00    280.00
2022-02-28 23:00:00+00:00    268.90
2022-03-01 00:00:00+00:00    258.46
Freq: 60T, Length: 2161, dtype: float64

In [23]:
# methods that return Pandas Series load
client.query_load(country_code, start=start,end=end)

                           Actual Load
2021-12-01 00:00:00+00:00       5620.0
2021-12-01 01:00:00+00:00       5285.0
2021-12-01 02:00:00+00:00       5020.0
2021-12-01 03:00:00+00:00       4878.0
2021-12-01 04:00:00+00:00       4805.0
...                                ...
2022-02-28 19:00:00+00:00       6988.0
2022-02-28 20:00:00+00:00       6894.0
2022-02-28 21:00:00+00:00       6508.0
2022-02-28 22:00:00+00:00       5997.0
2022-02-28 23:00:00+00:00       5533.0

[2160 rows x 1 columns]

In [24]:
# unavailability of generation units
client.query_unavailability_of_generation_units(country_code, start=start,end=end, docstatus=None)

,avail_qty,biddingzone_domain,businesstype,curvetype,docstatus,end,nominal_power,plant_type,production_resource_id,production_resource_location,production_resource_name,pstn,qty_uom,resolution,start
created_doc_time,,,,,,,,,,,,,,,
2021-12-02 19:30:16+00:00,0,PT,Planned maintenance,A03,None,2021-12-07 11:00:00+00:00,44.0,Hydro Run-of-river and poundage,16W-FRATEL-----A,NISA,Fratel,1,MAW,PT30M,2021-12-07 10:30:00+00:00
2021-12-02 19:30:18+00:00,0,PT,Planned maintenance,A03,None,2021-12-07 13:00:00+00:00,44.0,Hydro Run-of-river and poundage,16W-FRATEL-----A,NISA,Fratel,1,MAW,PT60M,2021-12-07 11:00:00+00:00
2021-12-02 19:30:19+00:00,0,PT,Planned maintenance,A03,None,2021-12-09 16:31:00+00:00,72.0,Hydro Pumped Storage,16WVFURNA------1,TERRAS DE BOURO,Vilarinho F.,1,MAW,PT1M,2021-12-09 16:30:00+00:00
2021-12-02 19:31:45+00:00,300,PT,Planned maintenance,A03,None,2021-12-07 08:00:00+00:00,390.0,Hydro Pumped Storage,16WFRADE2------F,VIEIRA DO MINHO,Frades II,1,MAW,PT60M,2021-11-25 09:00:00+00:00
2021-12-02 20:15:05+00:00,0,PT,Unplanned outage,A03,None,2021-12-02 18:45:00+00:00,53.0,Hydro Water Reservoir,16WCBODE-------5,TOMAR,Castelo Bode,1,MAW,PT1M,2021-12-02 18:32:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-02-21 12:19:16+00:00,0,PT,Unplanned outage,A03,None,2022-02-20 15:30:00+00:00,418.0,Fossil Gas,16WPEGO--------O,ABRANTES,Pego C.C.,1,MAW,PT15M,2022-02-20 15:15:00+00:00
2022-02-21 16:06:42+00:00,0,PT,Planned maintenance,A03,None,2022-02-22 17:00:00+00:00,134.0,Hydro Pumped Storage,16WFOZT--------Y,ALIJÓ,Foz Tua,1,MAW,PT60M,2022-01-01 00:00:00+00:00
2022-02-22 15:04:49+00:00,300,PT,Planned maintenance,A03,None,2022-02-22 14:59:00+00:00,390.0,Hydro Pumped Storage,16WFRADE2------F,VIEIRA DO MINHO,Frades II,1,MAW,PT1M,2022-02-22 14:45:00+00:00
2022-02-22 19:29:39+00:00,0,PT,Unplanned outage,A03,None,2022-02-22 15:15:00+00:00,390.0,Hydro Pumped Storage,16WFRADE2------F,VIEIRA DO MINHO,Frades II,1,MAW,PT1M,2022-02-22 15:06:00+00:00
2022-02-23 17:24:48+00:00,0,PT,Planned maintenance,A03,None,2022-02-23 17:19:00+00:00,112.0,Hydro Pumped Storage,16WAGUIE-------3,PENACOVA,Aguieira,1,MAW,PT1M,2022-02-23 17:15:00+00:00

In [25]:
#generation
client.query_generation(country_code, start=start,end=end, psr_type=None)

                                    Biomass        Fossil Gas  \
                          Actual Aggregated Actual Aggregated
2021-12-01 00:00:00+00:00             395.0            2388.0
2021-12-01 01:00:00+00:00             391.0            2218.0
2021-12-01 02:00:00+00:00             391.0            2076.0
2021-12-01 03:00:00+00:00             395.0            2077.0
2021-12-01 04:00:00+00:00             398.0            2072.0
...                                     ...               ...
2022-02-28 19:00:00+00:00             364.0            3012.0
2022-02-28 20:00:00+00:00             367.0            2719.0
2022-02-28 21:00:00+00:00             373.0            2626.0
2022-02-28 22:00:00+00:00             359.0            2485.0
2022-02-28 23:00:00+00:00             364.0            2237.0

                                              Fossil Hard coal  \
                          Actual Consumption Actual Aggregated
2021-12-01 00:00:00+00:00                4.0               0.0
2021-12-01 01:00:00+00:00                2.0               0.0
2021-12-01 02:00:00+00:00                1.0               0.0
2021-12-01 03:00:00+00:00                1.0               0.0
2021-12-01 04:00:00+00:00                1.0               0.0
...                                      ...               ...
2022-02-28 19:00:00+00:00                0.0               0.0
2022-02-28 20:00:00+00:00                2.0               0.0
2022-02-28 21:00:00+00:00                4.0               0.0
2022-02-28 22:00:00+00:00                2.0               0.0
2022-02-28 23:00:00+00:00                2.0               0.0

                                             Hydro Pumped Storage  \
                          Actual Consumption    Actual Aggregated
2021-12-01 00:00:00+00:00                3.0                489.0
2021-12-01 01:00:00+00:00                3.0                404.0
2021-12-01 02:00:00+00:00                4.0                354.0
2021-12-01 03:00:00+00:00                4.0                  0.0
2021-12-01 04:00:00+00:00                3.0                  0.0
...                                      ...                  ...
2022-02-28 19:00:00+00:00                0.0               1517.0
2022-02-28 20:00:00+00:00                0.0               1300.0
2022-02-28 21:00:00+00:00                0.0                292.0
2022-02-28 22:00:00+00:00                0.0                  1.0
2022-02-28 23:00:00+00:00                0.0                  0.0

                                             Hydro Run-of-river and poundage  \
                          Actual Consumption               Actual Aggregated
2021-12-01 00:00:00+00:00                2.0                           191.0
2021-12-01 01:00:00+00:00                2.0                            91.0
2021-12-01 02:00:00+00:00                5.0                            24.0
2021-12-01 03:00:00+00:00              421.0                            23.0
2021-12-01 04:00:00+00:00              352.0                            22.0
...                                      ...                             ...
2022-02-28 19:00:00+00:00                1.0                          1131.0
2022-02-28 20:00:00+00:00                1.0                          1052.0
2022-02-28 21:00:00+00:00                3.0                           635.0
2022-02-28 22:00:00+00:00                6.0                           192.0
2022-02-28 23:00:00+00:00                5.0                            27.0

                                             Hydro Water Reservoir  \
                          Actual Consumption     Actual Aggregated
2021-12-01 00:00:00+00:00                2.0                 225.0
2021-12-01 01:00:00+00:00                2.0                  72.0
2021-12-01 02:00:00+00:00                2.0                  72.0
2021-12-01 03:00:00+00:00                2.0                  72.0
2021-12-01 04:00:00+00:00                2.0                  72.0
...                                      ...                   ...
2022-02-28 19:00:00+00:00                1.0                 234.0
2022-02-28 20:00:00+00:00                1.0                 231.0
2022-02-28 21:00:00+00:00                2.0                  50.0
2022-02-28 22:00:00+00:00                2.0                   0.0
2022-02-28 23:00:00+00:00                2.0                   0.0

                                                         Other  \
                          Actual Consumption Actual Aggregated
2021-12-01 00:00:00+00:00                1.0              37.0
2021-12-01 01:00:00+00:00                1.0              37.0
2021-12-01 02:00:00+00:00                1.0              38.0
2021-12-01 03:00:00+00:00                1.0              37.0
2021-12-01 04:00:00+00:00                1.0              38.0
...                                      ...               ...
2022-02-28 19:00:00+00:00                1.0              33.0
2022-02-28 20:00:00+00:00                1.0              33.0
2022-02-28 21:00:00+00:00                1.0              34.0
2022-02-28 22:00:00+00:00                1.0              33.0
2022-02-28 23:00:00+00:00                1.0              33.0

                                      Solar     Wind Offshore  \
                          Actual Aggregated Actual Aggregated
2021-12-01 00:00:00+00:00               0.0               0.0
2021-12-01 01:00:00+00:00               0.0               1.0
2021-12-01 02:00:00+00:00               0.0               2.0
2021-12-01 03:00:00+00:00               0.0               3.0
2021-12-01 04:00:00+00:00               0.0               3.0
...                                     ...               ...
2022-02-28 19:00:00+00:00               0.0               0.0
2022-02-28 20:00:00+00:00               0.0               0.0
2022-02-28 21:00:00+00:00               0.0               0.0
2022-02-28 22:00:00+00:00               0.0               1.0
2022-02-28 23:00:00+00:00               0.0               4.0

                               Wind Onshore
                          Actual Aggregated
2021-12-01 00:00:00+00:00             206.0
2021-12-01 01:00:00+00:00             315.0
2021-12-01 02:00:00+00:00             470.0
2021-12-01 03:00:00+00:00             790.0
2021-12-01 04:00:00+00:00            1052.0
...                                     ...
2022-02-28 19:00:00+00:00             264.0
2022-02-28 20:00:00+00:00             263.0
2022-02-28 21:00:00+00:00             273.0
2022-02-28 22:00:00+00:00             274.0
2022-02-28 23:00:00+00:00             310.0

[2160 rows x 15 columns]

### Real-world considerations for Requests

Things do not always go so nicely, particularly when using API's at scale.

We'll quickly cover some other common considerations when using API's, and outline how they can be solved.

#### Retries

Sometimes you can do everything perfectly, and send off a request but something on the web-server (or elsewhere) can go wrong and give a bad status code.
We don't want to silently ignore these errors or let them crash our program by raising an exception.

The first port of call is to retry the request again.

---

A hacky way to do this would be (**don't do this**):

``` python
import time
import requests

def get(url):
    try:
        r = requests.get(url)
        r.raise_for_status()  # raise an error on a bad status
    except:
        time.sleep(1)  # sleep for a bit in case that helps
        return get(url)  # try again
```



#### Authentication

Not all API's are open for immediate use. For example, some require you pay for access (e.g. the google maps API) and some require you to register for access first.

When you get access to a "closed" API, you will typically get an API key - a long string of letters and numbers - which is unique to you which you need to send along with any GET request you make to the API.
This lets the API know who you are and decide how to deal with your request.

Several different types of authentication exists (read the specific API docs) but the most common way is:
``` python
api_key = 'asodifhafglkkhj'
r = requests.get(url, auth=(api_key, ''))
```

#### Rate limits

API's can be costly to host and typically limit the number of requests that can be made (either by an IP or API key).
If you exceed this limit you'll get a `429` status code for any extra requests you make (and may be blocked if you continue making them).

It is important to therefore respect any rate limits given in an API's documentation (annoyingly some are very vague).
The simplest way to do this is to limit how often the number of times our function that makes the request can be called within some time limit using the [ratelim](https://pypi.org/project/ratelim/) library - again using decorators.